### ISSUE TITLE
[Feature Request] Add a log out button

### ISSUE THREAD

**Issue by BigVirusBoi** [StaffOverseer/StaffOverseer-IssueTracker#5]
### Is your feature request related to a problem? Please describe.
I am frustrated as I am unable to log out of my account!

### Describe the solution you'd like
Rename the button "Go to Login" to "Log out" in the account dashboard.
This would also mean that going to the login page already logged in should redirect you to the dashboard.

### Describe alternatives you've considered
Deleting my LOCAL STORAGE?????

### Additional context
Here is an image of the area:
![image](https://github.com/user-attachments/assets/21ac2556-5508-49f7-8806-1d5c00706340)

**Comment by PerOdin** [comment]
Logout button has been added to work for now. Will be changed but the button wont go away so I'll close this issue.
https://staffoverseer.com/dashboard#:~:text=View%20Team-,Logout,-%C2%A9%202024%20StaffOverseer%20%2D%20All
