### ISSUE TITLE
The toggle light/dark mode button only works once

### ISSUE THREAD

**Issue by BigVirusBoi** [StaffOverseer/StaffOverseer-IssueTracker#7]
**Describe the bug**
The dark mode button only toggles the theme once per page.

**To Reproduce**
1. Go on any page
2. Click the toggle dark mode button
3. Click the button again
4. Navigate to another page
5. Click the toggle button

**Expected behavior**
Should be able to toggle multiple times per "page"

**Comment by PerOdin** [comment]
Okay the issue has been fixed. Also made it easier to be used in newer pages

**Comment by BigVirusBoi** [comment]
:O thank you so much staff overseer developer! IT WORKS!!!!
