### ISSUE TITLE
Unable to create new roles

### ISSUE THREAD

**Issue by BigVirusBoi** [StaffOverseer/StaffOverseer-IssueTracker#8]
Getting a "Some permissions are invalid" error
Happens with every role permission

**To Reproduce**
1. Select any permission
2. Create the role

**Expected behavior**
Role should be created with permissions

**Screenshots**
![image](https://github.com/user-attachments/assets/d655598a-f9cd-47d3-9338-4795287d3696)

**Comment by PerOdin** [comment]
The problem should be fixed now. Unable to recreate the issue on website as least.
