### ISSUE TITLE
[Feature Request] Bug report link on website

### ISSUE THREAD

**Issue by BigVirusBoi** [StaffOverseer/StaffOverseer-IssueTracker#9]
### Is your feature request related to a problem? Please describe.
Yes, this repository (and github organization) is not listed anywhere on the website.

### Describe the solution you'd like
Add a "Bug report" link to the footer redirecting you to this repo.

**Comment by PerOdin** [comment]
In the footer there has now been added a link to the issuetracker. 
It can be found here: https://staffoverseer.com/#:~:text=All%20Rights%20Reserved-,Report%20an%20issue,-Contact%20Us
